[tool.poetry]
name = "nino"
version = "0.2.0"
description = "A small unofficial AniList API wrapper made for python"
authors = ["Andy <yrisxl@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/an-dyy/nino"
repository = "https://github.com/an-dyy/nino"
keywords = ["AniList"]
packages = [{include = "nino"}]
include = ["LICENSE"]

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.26.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.2"
pytest = "^6.2.4"
mkdocs = "^1.2.1"
mkdocstrings = "^0.15.2"
mkdocs-material = "^7.1.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
